export const GET_ALL_VOITURE = "GET_ALL_VOITURE";
export const GET_ALL_VOITURE_FAIL = "GET_ALL_VOITURE_FAIL";
export const GET_VOITURE_REQUEST = "GET_VOITURE_REQUEST";

export const LOGIN_SUCCES = " LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const REGISTER_SUCCES = "  REGISTER_SUCCES";
export const REGISTER_FAIL = " REGISTER_FAIL";

export const GET_USER_SUCCES = " GET_USER_SUCCES";
export const GET_USER_FAIL = " GET_USER_FAIL";
export const GET_USER_REQUEST = "GET_USER_REQUEST";

export const GET_BYID_VOITURE = "GET_BYID_VOITURE";
export const GET_BYID_VOITURE_FAIL = "GET_BYID_VOITURE_FAIL";
export const GET_VOITURE_BYID_REQUEST = "GET_VOITURE_BYID_REQUEST";

export const ADD_COMMENT_SUCCES = "ADD_COMMENT_SUCCES";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
